import type { ClassConfig } from '../types';

export const CLASSES: ClassConfig[] = [
  {
    id: 'warrior',
    name: 'Warrior',
    description: 'A sturdy melee fighter. Hits all enemies in a short arc slash.',
    hp: 120,
    speed: 3.5,
    damage: 1,
    armor: 0.15,
    passive: '+15% Armor',
    startingWeaponId: 'boneDagger',
    cost: 0,
    quest: '',
    free: true,
    color: '#c8a060',
  },
  {
    id: 'mage',
    name: 'Mage',
    description: 'A spellcaster with a homing bolt that pierces one enemy.',
    hp: 90,
    speed: 3.5,
    damage: 1,
    armor: 0,
    passive: '+10% Area',
    startingWeaponId: 'crackedWand',
    cost: 0,
    quest: '',
    free: true,
    color: '#5588cc',
  },
  {
    id: 'pyromancer',
    name: 'Pyromancer',
    description: 'Orbiting flame ring burns nearby enemies. Kills leave a burning patch.',
    hp: 100,
    speed: 3.3,
    damage: 1,
    armor: 0,
    passive: 'Kills leave a 2s burning patch',
    startingWeaponId: 'fireBrazier',
    cost: 750,
    quest: 'fireStarter',
    free: false,
    color: '#cc5520',
  },
  {
    id: 'ranger',
    name: 'Ranger',
    description: 'Long-range piercing arrows with higher crit chance.',
    hp: 95,
    speed: 3.7,
    damage: 1,
    armor: 0,
    passive: '+15% Crit Chance',
    startingWeaponId: 'longbow',
    cost: 1000,
    quest: 'marksman',
    free: false,
    color: '#4a8a4a',
  },
  {
    id: 'necromancer',
    name: 'Necromancer',
    description: 'Summons a skeleton minion that auto-attacks. Heals on hit.',
    hp: 85,
    speed: 3.4,
    damage: 1,
    armor: 0,
    passive: '+12% Lifesteal',
    startingWeaponId: 'grimwalker',
    cost: 1250,
    quest: 'raiseTheDead',
    free: false,
    color: '#6a9a6a',
  },
  {
    id: 'berserker',
    name: 'Berserker',
    description: 'Dual cleavers hit very fast. Gets stronger as HP drops.',
    hp: 130,
    speed: 3.6,
    damage: 1,
    armor: 0,
    passive: '+1% Damage per 1% missing HP (cap 40%)',
    startingWeaponId: 'twinCleavers',
    cost: 1000,
    quest: 'bloodFrenzy',
    free: false,
    color: '#aa3330',
  },
  {
    id: 'frostWarden',
    name: 'Frost Warden',
    description: 'Frost shards slow enemies on hit. Extra damage to slowed foes.',
    hp: 100,
    speed: 3.4,
    damage: 1,
    armor: 0,
    passive: '+10% dmg to slowed enemies near you',
    startingWeaponId: 'rimeShard',
    cost: 1500,
    quest: 'coldSnap',
    free: false,
    color: '#44bbcc',
  },
  {
    id: 'bloodCultist',
    name: 'Blood Cultist',
    description: 'Heals from damage dealt. Gains attack speed at low HP.',
    hp: 100,
    speed: 3.5,
    damage: 1,
    armor: 0,
    passive: 'Sub-30% HP grants +20% Atk Speed for 5s (60s CD)',
    startingWeaponId: 'sanguineSickle',
    cost: 1750,
    quest: 'bloodPact',
    free: false,
    color: '#bb2244',
  },
];

export function getClass(id: string): ClassConfig {
  return CLASSES.find(c => c.id === id) ?? CLASSES[0];
}
