import type { QuestConfig } from '../types';

export const QUESTS: QuestConfig[] = [
  // Class quests
  { id: 'fireStarter', name: 'Fire Starter', description: 'Kill 100 enemies', target: 100, type: 'cumulative', reward: { type: 'class', id: 'pyromancer' } },
  { id: 'marksman', name: 'Marksman', description: 'Survive 3 minutes in a single run', target: 180, type: 'survival', reward: { type: 'class', id: 'ranger' } },
  { id: 'raiseTheDead', name: 'Raise the Dead', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'class', id: 'necromancer' } },
  { id: 'bloodFrenzy', name: 'Blood Frenzy', description: 'Reach Danger Level 5', target: 5, type: 'stat', statKey: 'highestDangerLevel', reward: { type: 'class', id: 'berserker' } },
  { id: 'coldSnap', name: 'Cold Snap', description: 'Kill 500 enemies', target: 500, type: 'cumulative', reward: { type: 'class', id: 'frostWarden' } },
  { id: 'bloodPact', name: 'Blood Pact', description: 'Kill 750 enemies', target: 750, type: 'cumulative', reward: { type: 'class', id: 'bloodCultist' } },

  // Tome quests
  { id: 'wideReach', name: 'Wide Reach', description: 'Kill 50 enemies', target: 50, type: 'cumulative', reward: { type: 'tome', id: 'areaSize' } },
  { id: 'moreIsMore', name: 'More Is More', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'tome', id: 'projectileCount' } },
  { id: 'straightThrough', name: 'Straight Through', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'tome', id: 'pierce' } },
  { id: 'sharpenedFocus', name: 'Sharpened Focus', description: 'Kill 80 enemies', target: 80, type: 'cumulative', reward: { type: 'tome', id: 'critChance' } },
  { id: 'vitalStrike', name: 'Vital Strike', description: 'Kill 80 enemies', target: 80, type: 'cumulative', reward: { type: 'tome', id: 'critDamage' } },
  { id: 'thickHide', name: 'Thick Hide', description: 'Survive 2 minutes', target: 120, type: 'survival', reward: { type: 'tome', id: 'armor' } },
  { id: 'evasiveManeuvers', name: 'Evasive Maneuvers', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'tome', id: 'dodge' } },
  { id: 'painfulRetribution', name: 'Painful Retribution', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'tome', id: 'thorns' } },
  { id: 'fastLearner', name: 'Fast Learner', description: 'Kill 50 enemies', target: 50, type: 'cumulative', reward: { type: 'tome', id: 'xpGain' } },
  { id: 'wideNet', name: 'Wide Net', description: 'Kill 30 enemies', target: 30, type: 'cumulative', reward: { type: 'tome', id: 'pickupRadius' } },
  { id: 'fortunesFavor', name: "Fortune's Favor", description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'tome', id: 'luck' } },
  { id: 'coinCounter', name: 'Coin Counter', description: 'Kill 80 enemies', target: 80, type: 'cumulative', reward: { type: 'tome', id: 'goldGain' } },
  { id: 'thirstForLife', name: 'Thirst for Life', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'tome', id: 'lifesteal' } },
  { id: 'finishTheJob', name: 'Finish the Job', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'tome', id: 'executioner' } },
  { id: 'bigGameHunter', name: 'Big Game Hunter', description: 'Kill 300 enemies', target: 300, type: 'cumulative', reward: { type: 'tome', id: 'eliteHunter' } },
  { id: 'firstStrike', name: 'First Strike', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'tome', id: 'bonebreaker' } },
  { id: 'wearThemDown', name: 'Wear Them Down', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'tome', id: 'marked' } },
  { id: 'kickThemWhileDown', name: 'Kick Them While Down', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'tome', id: 'opportunist' } },
  { id: 'unbreakable', name: 'Unbreakable', description: 'Survive 5 minutes', target: 300, type: 'survival', reward: { type: 'tome', id: 'undying' } },
  { id: 'crimsonPrecision', name: 'Crimson Precision', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'tome', id: 'vampiricEdge' } },
  { id: 'wasteNot', name: 'Waste Not', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'tome', id: 'hoarder' } },
  { id: 'weathered', name: 'Weathered', description: 'Survive 8 minutes', target: 480, type: 'survival', reward: { type: 'tome', id: 'adaptiveArmor' } },
  { id: 'lastStand', name: 'Last Stand', description: 'Survive 10 minutes', target: 600, type: 'survival', reward: { type: 'tome', id: 'bulwark' } },

  // Relic quests
  { id: 'chainReaction', name: 'Chain Reaction', description: 'Kill 300 enemies', target: 300, type: 'cumulative', reward: { type: 'relic', id: 'explosiveKills' } },
  { id: 'staticDischarge', name: 'Static Discharge', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'relic', id: 'chainSpark' } },
  { id: 'doubleTap', name: 'Double Tap', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'twinStrike' } },
  { id: 'killStreak', name: 'Kill Streak', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'relic', id: 'frenzy' } },
  { id: 'thinTheHerd', name: 'Thin the Herd', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'relic', id: 'enemySpawnDown' } },
  { id: 'coldTouch', name: 'Cold Touch', description: 'Kill 100 enemies', target: 100, type: 'cumulative', reward: { type: 'relic', id: 'slowField' } },
  { id: 'slowTheWorld', name: 'Slow the World', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'relic', id: 'timeDilation' } },
  { id: 'reapWhatYouSow', name: 'Reap What You Sow', description: 'Kill 120 enemies', target: 120, type: 'cumulative', reward: { type: 'relic', id: 'soulHarvest' } },
  { id: 'gracePeriod', name: 'Grace Period', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'nullField' } },
  { id: 'keepMoving', name: 'Keep Moving', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'relic', id: 'momentumShield' } },
  { id: 'twoForOne', name: 'Two for One', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'reapersBargain' } },
  { id: 'smokeAndMirrors', name: 'Smoke and Mirrors', description: 'Kill 180 enemies', target: 180, type: 'cumulative', reward: { type: 'relic', id: 'mirrorImage' } },
  { id: 'shockTherapy', name: 'Shock Therapy', description: 'Kill 220 enemies', target: 220, type: 'cumulative', reward: { type: 'relic', id: 'staticField' } },
  { id: 'volatile', name: 'Volatile', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'unstableCore' } },
  { id: 'watchedOver', name: 'Watched Over', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'relic', id: 'guardianSpirit' } },
  { id: 'secondBreath', name: 'Second Breath', description: 'Survive 4 minutes', target: 240, type: 'survival', reward: { type: 'relic', id: 'adrenaline' } },
  { id: 'cheatDeath', name: 'Cheat Death', description: 'Survive 6 minutes', target: 360, type: 'survival', reward: { type: 'relic', id: 'secondWind' } },
  { id: 'oneMoreLife', name: 'One More Life', description: 'Survive 10 minutes', target: 600, type: 'survival', reward: { type: 'relic', id: 'phoenixAsh' } },
  { id: 'bloodAura', name: 'Blood Aura', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'vampiricAura' } },
  { id: 'gravityWell', name: 'Gravity Well', description: 'Kill 120 enemies', target: 120, type: 'cumulative', reward: { type: 'relic', id: 'magnetPulse' } },
  { id: 'vaultHunter', name: 'Vault Hunter', description: 'Kill 100 enemies', target: 100, type: 'cumulative', reward: { type: 'relic', id: 'treasureSense' } },
  { id: 'pocketsFull', name: 'Pockets Full', description: 'Kill 80 enemies', target: 80, type: 'cumulative', reward: { type: 'relic', id: 'scavenger' } },
  { id: 'allIn', name: 'All In', description: 'Kill 150 enemies', target: 150, type: 'cumulative', reward: { type: 'relic', id: 'glassCannon' } },
  { id: 'overload', name: 'Overload', description: 'Kill 120 enemies', target: 120, type: 'cumulative', reward: { type: 'relic', id: 'overcharge' } },
  { id: 'getRichQuick', name: 'Get Rich Quick', description: 'Kill 100 enemies', target: 100, type: 'cumulative', reward: { type: 'relic', id: 'goldRush' } },
  { id: 'noBrakes', name: 'No Brakes', description: 'Kill 100 enemies', target: 100, type: 'cumulative', reward: { type: 'relic', id: 'recklessMomentum' } },
  { id: 'embraceThePain', name: 'Embrace the Pain', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'berserkBlood' } },
  { id: 'ringTheBell', name: 'Ring the Bell', description: 'Kill 220 enemies', target: 220, type: 'cumulative', reward: { type: 'relic', id: 'swarmCall' } },
  { id: 'hungryGhost', name: 'Hungry Ghost', description: 'Kill 250 enemies', target: 250, type: 'cumulative', reward: { type: 'relic', id: 'vampiresCurse' } },
  { id: 'plantedFeet', name: 'Planted Feet', description: 'Kill 200 enemies', target: 200, type: 'cumulative', reward: { type: 'relic', id: 'momentumBreaker' } },
  { id: 'bigKillsBigSpeed', name: 'Big Kills, Big Speed', description: 'Kill 5 Elite/Veteran enemies', target: 5, type: 'cumulative', reward: { type: 'relic', id: 'momentumSurge' } },

  // Weapon quests
  { id: 'eyeOfTheStorm', name: 'Eye of the Storm', description: 'Kill 300 enemies', target: 300, type: 'cumulative', reward: { type: 'weapon', id: 'tornado' } },
  { id: 'playingWithFire', name: 'Playing With Fire', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'weapon', id: 'fireball' } },
  { id: 'boomerang', name: 'Boomerang', description: 'Kill 400 enemies', target: 400, type: 'cumulative', reward: { type: 'weapon', id: 'chakram' } },
  { id: 'fallingSky', name: 'Falling Sky', description: 'Kill 450 enemies', target: 450, type: 'cumulative', reward: { type: 'weapon', id: 'meteorStorm' } },
  { id: 'chainReactionII', name: 'Chain Reaction II', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'weapon', id: 'lightningStaff' } },
  { id: 'slowPoison', name: 'Slow Poison', description: 'Kill 300 enemies', target: 300, type: 'cumulative', reward: { type: 'weapon', id: 'poisonFlask' } },
  { id: 'oneShot', name: 'One Shot', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'weapon', id: 'javelin' } },
  { id: 'deepFreeze', name: 'Deep Freeze', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'weapon', id: 'frostBomb' } },
  { id: 'whirlingDeath', name: 'Whirling Death', description: 'Kill 400 enemies', target: 400, type: 'cumulative', reward: { type: 'weapon', id: 'bladeStorm' } },
  { id: 'ghostPack', name: 'Ghost Pack', description: 'Kill 500 enemies', target: 500, type: 'cumulative', reward: { type: 'weapon', id: 'spectralHounds' } },
  { id: 'reelItIn', name: 'Reel It In', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'weapon', id: 'bloodChain' } },
  { id: 'callTheStorm', name: 'Call the Storm', description: 'Kill 400 enemies', target: 400, type: 'cumulative', reward: { type: 'weapon', id: 'stormTotem' } },
  { id: 'coldGround', name: 'Cold Ground', description: 'Kill 350 enemies', target: 350, type: 'cumulative', reward: { type: 'weapon', id: 'glacierSpike' } },
];

export function getQuest(id: string): QuestConfig | undefined {
  return QUESTS.find(q => q.id === id);
}
