import type { WeaponConfig } from '../types';

export const STARTING_WEAPONS: WeaponConfig[] = [
  {
    id: 'boneDagger',
    name: 'Bone Dagger',
    description: 'Melee arc slash, hits all enemies in a short arc.',
    baseDamage: 12,
    baseCooldown: 0.9,
    range: 50,
    area: 50,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'A jagged shard of bone.',
    type: 'melee',
  },
  {
    id: 'crackedWand',
    name: 'Cracked Wand',
    description: 'Slow homing bolt that pierces 1 enemy.',
    baseDamage: 9,
    baseCooldown: 1.1,
    range: 300,
    area: 20,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'Cracked but still sparks.',
    type: 'ranged',
    projectileCount: 1,
    pierce: 1,
    homing: true,
  },
  {
    id: 'fireBrazier',
    name: 'Fire Brazier',
    description: 'Orbiting flame ring, tick damage.',
    baseDamage: 6,
    baseCooldown: 0.5,
    range: 70,
    area: 70,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'An eternal brazier flame.',
    type: 'orbit',
    tickRate: 0.5,
  },
  {
    id: 'longbow',
    name: 'Longbow',
    description: 'Straight-line piercing arrow, long range.',
    baseDamage: 16,
    baseCooldown: 1.3,
    range: 500,
    area: 15,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'A well-strung hunting bow.',
    type: 'line',
    projectileCount: 1,
    pierce: 3,
  },
  {
    id: 'grimwalker',
    name: 'Grimwalker',
    description: 'Auto-attacking skeleton minion, 60 HP, respawns in 8s.',
    baseDamage: 8,
    baseCooldown: 1.0,
    range: 250,
    area: 30,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'A loyal bone servant.',
    type: 'summon',
  },
  {
    id: 'twinCleavers',
    name: 'Twin Cleavers',
    description: 'Dual-wield very fast short-range hits.',
    baseDamage: 7,
    baseCooldown: 0.5,
    range: 40,
    area: 40,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'Two is better than one.',
    type: 'melee',
    projectileCount: 2,
  },
  {
    id: 'rimeShard',
    name: 'Rime Shard Launcher',
    description: 'Ranged, applies 20% slow for 2s on hit.',
    baseDamage: 11,
    baseCooldown: 1.4,
    range: 350,
    area: 15,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'Frost crystallized into shards.',
    type: 'line',
    projectileCount: 1,
    pierce: 1,
  },
  {
    id: 'sanguineSickle',
    name: 'Sanguine Sickle',
    description: 'Melee, heals 8% of damage dealt.',
    baseDamage: 10,
    baseCooldown: 1.0,
    range: 55,
    area: 55,
    cost: 0,
    quest: '',
    free: true,
    flavor: 'Curved blade, bloodstained.',
    type: 'melee',
  },
];

export const EXTRA_WEAPONS: WeaponConfig[] = [
  {
    id: 'tornado',
    name: 'Tornado',
    description: 'Drifts to nearest cluster, pulls & tick-damages.',
    baseDamage: 5,
    baseCooldown: 0.4,
    range: 90,
    area: 90,
    cost: 2200,
    quest: 'eyeOfTheStorm',
    free: false,
    flavor: 'A hungry vortex.',
    type: 'aoe',
    tickRate: 0.4,
    shopOnly: true,
  },
  {
    id: 'fireball',
    name: 'Fireball',
    description: 'Arcing lobbed shot, explodes on impact.',
    baseDamage: 20,
    baseCooldown: 1.6,
    range: 350,
    area: 60,
    cost: 2600,
    quest: 'playingWithFire',
    free: false,
    flavor: 'Boom.',
    type: 'ranged',
    shopOnly: true,
  },
  {
    id: 'chakram',
    name: 'Chakram',
    description: 'Thrown disc, hits outbound and return.',
    baseDamage: 9,
    baseCooldown: 1.2,
    range: 400,
    area: 20,
    cost: 3000,
    quest: 'boomerang',
    free: false,
    flavor: 'Always comes back.',
    type: 'thrown',
    projectileCount: 1,
    shopOnly: true,
  },
  {
    id: 'meteorStorm',
    name: 'Meteor Storm',
    description: 'Calls meteors on random nearby enemies, 1s telegraph.',
    baseDamage: 28,
    baseCooldown: 3.5,
    range: 400,
    area: 55,
    cost: 3200,
    quest: 'fallingSky',
    free: false,
    flavor: 'The sky is falling.',
    type: 'aoe',
    shopOnly: true,
  },
  {
    id: 'lightningStaff',
    name: 'Lightning Staff',
    description: 'Zaps nearest enemy, chains to 2 more.',
    baseDamage: 14,
    baseCooldown: 1.0,
    range: 320,
    area: 120,
    cost: 2800,
    quest: 'chainReactionII',
    free: false,
    flavor: 'Zap zap zap.',
    type: 'ranged',
    shopOnly: true,
  },
  {
    id: 'poisonFlask',
    name: 'Poison Flask',
    description: 'Thrown flask, lingering poison cloud.',
    baseDamage: 4,
    baseCooldown: 0.6,
    range: 300,
    area: 60,
    cost: 2400,
    quest: 'slowPoison',
    free: false,
    flavor: 'Toxic brew.',
    type: 'aoe',
    tickRate: 0.6,
    shopOnly: true,
  },
  {
    id: 'javelin',
    name: 'Javelin',
    description: 'Heavy piercing spear, pierces 2.',
    baseDamage: 32,
    baseCooldown: 2.0,
    range: 550,
    area: 20,
    cost: 2600,
    quest: 'oneShot',
    free: false,
    flavor: 'One throw, one kill.',
    type: 'line',
    pierce: 2,
    shopOnly: true,
  },
  {
    id: 'frostBomb',
    name: 'Frost Bomb',
    description: 'Detonates, fully freezes enemies 1s.',
    baseDamage: 12,
    baseCooldown: 2.2,
    range: 300,
    area: 65,
    cost: 2800,
    quest: 'deepFreeze',
    free: false,
    flavor: 'Absolute zero.',
    type: 'aoe',
    shopOnly: true,
  },
  {
    id: 'bladeStorm',
    name: 'Blade Storm',
    description: '3 blades orbit at shifting radius, pierce all.',
    baseDamage: 6,
    baseCooldown: 0.4,
    range: 90,
    area: 90,
    cost: 3000,
    quest: 'whirlingDeath',
    free: false,
    flavor: 'Whirling doom.',
    type: 'orbit',
    tickRate: 0.4,
    shopOnly: true,
  },
  {
    id: 'spectralHounds',
    name: 'Spectral Hounds',
    description: '2 ghost hounds dash through clusters.',
    baseDamage: 10,
    baseCooldown: 2.5,
    range: 200,
    area: 40,
    cost: 3400,
    quest: 'ghostPack',
    free: false,
    flavor: 'Ghostly howls.',
    type: 'ranged',
    shopOnly: true,
  },
  {
    id: 'bloodChain',
    name: 'Blood Chain',
    description: 'Hooks furthest enemy, yanks and bursts.',
    baseDamage: 24,
    baseCooldown: 1.8,
    range: 300,
    area: 40,
    cost: 2600,
    quest: 'reelItIn',
    free: false,
    flavor: 'Get over here!',
    type: 'ranged',
    shopOnly: true,
  },
  {
    id: 'stormTotem',
    name: 'Storm Totem',
    description: 'Stationary totem strikes lightning periodically.',
    baseDamage: 18,
    baseCooldown: 1.5,
    range: 200,
    area: 200,
    cost: 3000,
    quest: 'callTheStorm',
    free: false,
    flavor: 'A localized storm.',
    type: 'summon',
    shopOnly: true,
  },
  {
    id: 'glacierSpike',
    name: 'Glacier Spike',
    description: 'Ice spike erupts under nearest enemy, knockup.',
    baseDamage: 22,
    baseCooldown: 1.7,
    range: 300,
    area: 40,
    cost: 2700,
    quest: 'coldGround',
    free: false,
    flavor: 'Impaled on ice.',
    type: 'ranged',
    shopOnly: true,
  },
];

export const ALL_WEAPONS = [...STARTING_WEAPONS, ...EXTRA_WEAPONS];

export function getWeapon(id: string): WeaponConfig {
  return ALL_WEAPONS.find(w => w.id === id) ?? STARTING_WEAPONS[0];
}

export const SHOP_TIERS = [
  { tier: 1, cost: 400, damageMult: 1.0, areaMult: 1.0, label: 'Buy' },
  { tier: 2, cost: 300, damageMult: 1.2, areaMult: 1.0, label: '+20% Dmg' },
  { tier: 3, cost: 600, damageMult: 1.4, areaMult: 1.15, label: '+20% Dmg, +15% Area' },
  { tier: 4, cost: 1000, damageMult: 1.65, areaMult: 1.15, label: '+25% Dmg' },
  { tier: 5, cost: 1600, damageMult: 1.95, areaMult: 1.15, label: '+30% Dmg + Flourish' },
];
